# -*- coding: utf-8 -*-
"""GAN3.6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nl5rDaVDG6WO_PtefFRvHRKcnELnA-nr
"""

import os
import zipfile
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from transformers import CLIPTokenizer, CLIPTextModel
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.optim as optim
import torchvision
import numpy as np

# --- Mount Google Drive ---
from google.colab import drive
drive.mount('/content/drive')

# --- Path Configuration ---
# Set your paths in Google Drive
DRIVE_BASE_PATH = '/content/drive/MyDrive/Mini project'  # Change this to your desired folder
DATA_ZIP_PATH = f'{DRIVE_BASE_PATH}/gdata.zip'  # Path to your zip file in Drive
MODEL_SAVE_PATH = f'{DRIVE_BASE_PATH}/model'  # Where to save models

# Create directories if they don't exist
os.makedirs(MODEL_SAVE_PATH, exist_ok=True)

# --- Extract dataset from Drive ---
extract_path = '/content/floorplan_data'
if not os.path.exists(extract_path):
    with zipfile.ZipFile(DATA_ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Unzip completed.")
else:
    print("Data already extracted.")

# --- Verify dataset ---
IMAGE_DIR = "/content/floorplan_data/gdata/images"
ANNOTATION_DIR = "/content/floorplan_data/gdata/annotations"
image_files = [f for f in os.listdir(IMAGE_DIR) if f.endswith('.png')]
annotation_files = [f for f in os.listdir(ANNOTATION_DIR) if f.endswith('.txt')]
matches = [f for f in image_files if f.replace('.png', '.txt') in annotation_files]

print(f"✅ Total images: {len(image_files)}")
print(f"✅ Total annotations: {len(annotation_files)}")
print(f"✅ Matched image-text pairs: {len(matches)}")

# --- Custom Dataset for Floor Plans ---
class FloorPlanDataset(Dataset):
    def __init__(self, image_dir, annotation_dir, transform=None):
        self.image_dir = image_dir
        self.annotation_dir = annotation_dir
        self.transform = transform
        self.image_files = [f for f in os.listdir(image_dir) if f.endswith('.png')]
        self.image_files = [f for f in self.image_files if f.replace('.png', '.txt') in os.listdir(annotation_dir)]

        # Initialize CLIP
        self.tokenizer = CLIPTokenizer.from_pretrained('openai/clip-vit-base-patch32')
        self.text_model = CLIPTextModel.from_pretrained('openai/clip-vit-base-patch32').to(device)
        self.text_model.eval()

        # Precompute all text embeddings
        self.text_embeddings = []
        print("Precomputing text embeddings...")
        for img_name in self.image_files:
            txt_name = img_name.replace('.png', '.txt')
            txt_path = os.path.join(self.annotation_dir, txt_name)
            with open(txt_path, 'r') as f:
                text = f.read().strip()

            # Tokenize and encode text
            inputs = self.tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=77)
            inputs = {k: v.to(device) for k, v in inputs.items()}
            with torch.no_grad():
                embedding = self.text_model(**inputs).last_hidden_state.mean(dim=1).squeeze(0)  # [512]
            self.text_embeddings.append(embedding.cpu())  # Store on CPU to save GPU memory

        self.text_embeddings = torch.stack(self.text_embeddings)  # [num_samples, 512]
        print(f"Text embeddings shape: {self.text_embeddings.shape}")
        assert len(self.image_files) == len(self.text_embeddings), "Mismatch between images and text embeddings!"

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        # Load image
        img_name = self.image_files[idx]
        img_path = os.path.join(self.image_dir, img_name)
        image = Image.open(img_path)  # Keep as RGB

        # Apply image transforms
        if self.transform:
            image = self.transform(image)

        # Get precomputed text embedding
        text_embed = self.text_embeddings[idx]

        return image, text_embed

    def collate_fn(self, batch):
        images, text_embeds = zip(*batch)
        images = torch.stack(images)  # [batch_size, 3, 64, 64]
        text_embeds = torch.stack(text_embeds)  # [batch_size, 512]
        text_embeds = text_embeds.to(device)
        return images, text_embeds

# --- Device and Hyperparameters ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
batch_size = 16
latent_dim = 100
text_embed_dim = 512  # CLIP embedding size
lr = 0.0002
beta1 = 0.5
num_epochs = 50
image_size = 64

# --- Image Transforms ---
transform = transforms.Compose([
    transforms.Resize((image_size, image_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # Normalize RGB to [-1, 1]
])

# --- Load Dataset ---
dataset = FloorPlanDataset(IMAGE_DIR, ANNOTATION_DIR, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True, collate_fn=dataset.collate_fn)

# --- Generator Model ---
class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.text_embed = nn.Linear(text_embed_dim, 64)  # Project CLIP embedding
        self.main = nn.Sequential(
            nn.ConvTranspose2d(latent_dim + 64, 512, 4, 1, 0, bias=False),
            nn.BatchNorm2d(512),
            nn.ReLU(True),
            nn.ConvTranspose2d(512, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(True),
            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(True),
            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),
            nn.ConvTranspose2d(64, 3, 4, 2, 1, bias=False),  # Output 3 channels (RGB)
            nn.Tanh()  # Output in [-1, 1]
        )

    def forward(self, noise, text_embeds):
        batch_size = noise.size(0)  # Get the batch size from noise
        text_out = self.text_embed(text_embeds)  # [batch_size, 64]
        text_out = text_out.view(batch_size, 64, 1, 1)  # [batch_size, 64, 1, 1]
        input_combined = torch.cat([noise, text_out], dim=1)  # Concatenate noise and text embedding
        return self.main(input_combined)

# --- Discriminator Model ---
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.text_embed = nn.Linear(text_embed_dim, 1 * 64 * 64)  # 512 to 4096
        self.main = nn.Sequential(
            nn.Conv2d(3 + 1, 64, 4, 2, 1, bias=False),  # 3 for RGB + 1 for text channel
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(256, 512, 4, 2, 1, bias=False),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(512, 1, 4, 1, 0, bias=False),
            nn.Sigmoid()
        )

    def forward(self, img, text_embeds):
        batch_size = img.size(0)  # Get the batch size from img
        text_out = self.text_embed(text_embeds)  # [batch_size, 4096]
        text_out = text_out.view(batch_size, 1, 64, 64)  # [batch_size, 1, 64, 64]
        input_combined = torch.cat([img, text_out], dim=1)  # Concatenate image and text channel
        return self.main(input_combined).view(-1)

# --- Initialize Models and Optimizers ---
netG = Generator().to(device)
netD = Discriminator().to(device)
criterion = nn.BCELoss()
optD = optim.Adam(netD.parameters(), lr=lr, betas=(beta1, 0.999))
optG = optim.Adam(netG.parameters(), lr=lr, betas=(beta1, 0.999))

# --- Training Loop ---
losses_G, losses_D = [], []
for epoch in range(num_epochs):
    print(f'Epoch [{epoch+1}/{num_epochs}]')
    for i, (real_imgs, text_embeds) in enumerate(dataloader):
        real_imgs = real_imgs.to(device)
        text_embeds = text_embeds.to(device)
        batch_size = real_imgs.size(0)

        # --- Train Discriminator ---
        netD.zero_grad()
        real_labels = torch.full((batch_size,), 0.9, device=device)
        output_real = netD(real_imgs, text_embeds)
        errD_real = criterion(output_real, real_labels)

        noise = torch.randn(batch_size, latent_dim, 1, 1, device=device)
        fake_imgs = netG(noise, text_embeds)
        fake_labels = torch.full((batch_size,), 0.1, device=device)
        output_fake = netD(fake_imgs.detach(), text_embeds)
        errD_fake = criterion(output_fake, fake_labels)

        real_imgs = real_imgs + 0.02 * torch.randn_like(real_imgs)
        real_imgs.clamp_(-1, 1)

        errD = errD_real + errD_fake
        errD.backward()
        optD.step()

        # --- Train Generator ---
        netG.zero_grad()
        fake_labels = torch.full((batch_size,), 1.0, device=device)
        output = netD(fake_imgs, text_embeds)
        errG = criterion(output, fake_labels)
        errG.backward()
        optG.step()
        losses_G.append(errG.item())
        losses_D.append(errD.item())

    # Save model weights to Google Drive
    torch.save(netG.state_dict(), f'{MODEL_SAVE_PATH}/generator_epoch_{epoch+1}.pth')
    torch.save(netD.state_dict(), f'{MODEL_SAVE_PATH}/discriminator_epoch_{epoch+1}.pth')

    # Visualize generated images
    with torch.no_grad():
        fake_imgs = netG(noise, text_embeds).detach().cpu()
        plt.figure(figsize=(8, 8))
        plt.imshow(np.transpose(torchvision.utils.make_grid(fake_imgs[:16], padding=2, normalize=True), (1, 2, 0)))
        plt.axis('off')
        plt.title(f'Generated Floor Plans at Epoch {epoch+1}')
        plt.show()

# --- Generation Function ---
def generate_floor_plan(text, model_path, device, latent_dim=100, image_size=64):
    # Initialize CLIP
    tokenizer = CLIPTokenizer.from_pretrained('openai/clip-vit-base-patch32')
    text_model = CLIPTextModel.from_pretrained('openai/clip-vit-base-patch32').to(device)
    text_model.eval()

    # Load Generator model
    netG = Generator().to(device)
    netG.load_state_dict(torch.load(model_path))
    netG.eval()

    # Process text input
    with torch.no_grad():
        inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=77)
        inputs = {k: v.to(device) for k, v in inputs.items()}
        text_embed = text_model(**inputs).last_hidden_state.mean(dim=1)  # [1, 512]

        # Generate image
        noise = torch.randn(1, latent_dim, 1, 1, device=device)
        fake_img = netG(noise, text_embed).detach().cpu().squeeze(0)  # [3, 64, 64]

        # Visualize
        plt.figure(figsize=(6, 6))
        plt.imshow(np.transpose(fake_img, (1, 2, 0)) * 0.5 + 0.5)  # Denormalize to [0, 1]
        plt.axis('off')
        plt.title('Generated Floor Plan')
        plt.show()

# Example usage after training
model_path = f'{MODEL_SAVE_PATH}/generator_epoch_{num_epochs}.pth'
text_description = input("Enter a text description for the floor plan: ")
generate_floor_plan(text_description, model_path, device)

import torch
from transformers import CLIPTokenizer, CLIPTextModel
import matplotlib.pyplot as plt
import numpy as np

# --- Set Device ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# --- Load Generator Model ---
def load_generator(model_path, device):
    netG = Generator().to(device)  # Use the same Generator class as before
    netG.load_state_dict(torch.load(model_path, map_location=device))
    netG.eval()  # Set to evaluation mode
    return netG

# Example: Load the last saved model
MODEL_PATH = '/content/drive/MyDrive/Mini project/model/generator_epoch_50.pth'
netG = load_generator(MODEL_PATH, device)

# --- Generate from Text ---
def generate_floorplan(text_description, netG, device, latent_dim=100):
    # Load CLIP (for text embeddings)
    tokenizer = CLIPTokenizer.from_pretrained('openai/clip-vit-base-patch32')
    text_model = CLIPTextModel.from_pretrained('openai/clip-vit-base-patch32').to(device)
    text_model.eval()

    # Encode text
    inputs = tokenizer(text_description, return_tensors="pt", padding=True, truncation=True, max_length=77)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        text_embed = text_model(**inputs).last_hidden_state.mean(dim=1)  # [1, 512]

    # Generate image
    noise = torch.randn(1, latent_dim, 1, 1, device=device)  # Random noise
    with torch.no_grad():
        generated_image = netG(noise, text_embed).cpu().squeeze(0)  # [3, 64, 64]

    # Display
    plt.imshow(np.transpose(generated_image, (1, 2, 0)) * 0.5 + 0.5)  # Convert from [-1,1] to [0,1]
    plt.axis('off')
    plt.title(text_description)
    plt.show()

# --- Ask User for Input ---
user_input = input("Describe the floor plan you want to generate (e.g., 'modern apartment with 2 bedrooms'): ")

# --- Generate Floor Plan ---
generate_floorplan(user_input, netG, device)
